# Generated by Django 5.2.15 on 2026-06-19 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="image",
            field=models.CharField(
                blank=True, max_length=500, null=True, verbose_name="Image URL"
            ),
        ),
    ]
